### ISSUE TITLE
移动设备设置代理后访问不了mitm证书下载页面

### ISSUE THREAD

**Issue by qkmaosjtu** [meituan/lyrebird#1]

**Comment by zhaoye** [comment]
举个例子：
lyrebird启动后所在IP为 a.a.a.a, 那么这时代理服务地址为a.a.a.a:4272, mock服务地址为a.a.a.a:9090
此时移动设备如果可以连通lyrebird， 在未设置代理的时候，在浏览器中应可以打开http://a.a.a.a:9090
如果上述操作正常，则可证明移动设备与lyrebird网络连接正常。这时设置代理也会生效。

请你这样检查一下。 @qkmaosjtu

**Comment by qkmaosjtu** [comment]
@zhaoye 
谢谢~我按照教程做了相关尝试：
![image](https://user-images.githubusercontent.com/16631352/42744714-0433938e-8901-11e8-891f-6b9493823862.png)
确保了代理设置代理正确：
![image](https://user-images.githubusercontent.com/16631352/42744725-163324d2-8901-11e8-9b80-07b6928e1219.png)
但设备仍然无法访问网络：
![image](https://user-images.githubusercontent.com/16631352/42744735-261ee232-8901-11e8-8e76-8317c4abe9f1.png)

**Comment by zhaoye** [comment]
排除一下环境问题先：
curl http://localhost:9090/mock/http://www.baidu.com
在电脑上试试这个是否可以

**Comment by qkmaosjtu** [comment]
环境补充：
python 3.6.6
Mac OS 10.13.2

**Comment by qkmaosjtu** [comment]
@zhaoye 
我们的网络限制问题
