### ISSUE TITLE
只有inspector和DataMagnager两个模块

### ISSUE THREAD

**Issue by ja89son** [meituan/lyrebird#4]
开发者你好：
我brew安装和下载ZIP两种方式安装，都只能看到标题中的两个模块，版本号为0.10.5。请问是什么情况？

谢谢

**Comment by Archer456** [comment]
@ja89son  你好  你是什么手机机型   我的无法下载pem.crt   你的可以正常下载安装pem.crt么？

我的界面  也是  只有inspecrot和datamanager

**Comment by zhaoye** [comment]
你好。目前默认没有集成插件。还是需要自己装的。
安装方式如下
`
pip3 install lyrebird-ios
pip3 install lyrebird-android
pip3 install lyrebird-api-coverage
`
@ja89son @Archer456

**Comment by ja89son** [comment]
@Archer456 IOS11.4，暂时没有尝试过别的手机

**Comment by ja89son** [comment]
@zhaoye 
谢谢答复，有mock的组件吗？我比较关心的是mock的相关功能。

**Comment by zhaoye** [comment]
mock是Lyrebird默认的功能。

**Comment by zhaoye** [comment]
是的。会陆续开放的。
目前有些部分和内部业务有耦合，需要解决后开放 :) 
@Archer456

**Comment by ja89son** [comment]
目前只是做了代理和监控吧， 构造reponse内容才算是mock的功能吧？这个也是插件吗？
我没有找到这个入口。
@zhaoye

**Comment by zhaoye** [comment]
支持mock的。录制数据后在DataManager里可以修改数据。 
也可以直接在本地修改数据。
@ja89son
