### ISSUE TITLE
小米手机设置代理和访问mitm.it 无法下载pem.crt

### ISSUE THREAD

**Issue by Archer456** [meituan/lyrebird#5]
hello  我根据help 已经部署启动了lyrebird
我本机是ubuntu18.04 用的公司无线wifi dhcp获得IP    手机是连接的公司同一wifi   

mitmproxy start on ×××.×××.×××.×××:4272  ***请在被测设备上设置代理服务器地址***

设置小米手机代理
https://jingyan.baidu.com/article/1974b2895cb780f4b1f774b5.html

被测设备上用浏览器打开 http://mitm.it  ​   选择Android 提示下载pem.crt 

从手机的 下载管理 里 看  是下载失败的   

这是下载管理中 点击重新下载后的 日志

`DEBUG - [connectionpool] - Starting new HTTP connection (1): api.tw06.xlmc.sec.miui.com:80
DEBUG - [connectionpool] - http://api.tw06.xlmc.sec.miui.com:80 "POST /api/configure/get HTTP/1.1" 200 None
INFO - [mock_server] - 200 proxy POST http://api.tw06.xlmc.sec.miui.com/api/configure/get
INFO - [mock_server] - 200  GET http://localhost:9090/api/flow
INFO - [proxy_flow] - https://stats.jpush.cn/v2/report
INFO - [proxy_flow] - Redirect-> http://localhost:9090/mock/https://stats.jpush.cn/v2/report
DEBUG - [connectionpool] - Starting new HTTPS connection (1): stats.jpush.cn:443
DEBUG - [connectionpool] - https://stats.jpush.cn:443 "POST /v2/report HTTP/1.1" 200 None
INFO - [mock_server] - 200 proxy POST https://stats.jpush.cn/v2/report
INFO - [mock_server] - 200  GET http://localhost:9090/api/flow
INFO - [proxy_flow] - https://stats.jpush.cn/v2/report
INFO - [proxy_flow] - Redirect-> http://localhost:9090/mock/https://stats.jpush.cn/v2/report
DEBUG - [connectionpool] - Starting new HTTPS connection (1): stats.jpush.cn:443
DEBUG - [connectionpool] - https://stats.jpush.cn:443 "POST /v2/report HTTP/1.1" 200 None
INFO - [mock_server] - 200 proxy POST https://stats.jpush.cn/v2/report
INFO - [mock_server] - 200  GET http://localhost:9090/api/flow
`

**Comment by Archer456** [comment]
![image](https://user-images.githubusercontent.com/18392901/42793663-b8480218-89ad-11e8-82c4-96d526f00903.png)
感觉被安全限制了？

**Comment by Archer456** [comment]
对 没错  我是用的小米手机自带浏览器访问的话，从日志来看  是被小米的安全服务给限制了。
我尝试了下用手机里的Firefox 不行。。

又用了下手机里的 Chrome 版本67.0.3396.87 应该是最新的。 访问 http://mitm.it ​ 

会提示下图  自己取个名字lyrebird 确定 即会提示你安装成功了。

现在可以正常record app 请求了。

**Comment by zhaoye** [comment]
十分感谢您的反馈~~
