### ISSUE TITLE
ERROR - [device_service] - No libimobiledevice program found, See README Help Center

### ISSUE THREAD

**Issue by Archer456** [meituan/lyrebird#6]
我已经正常访问android界面　看到实时日志　和　截图screen shot真机界面了　　为什么lyrebird v的日志会不时的　出现该句错误　　
ERROR - [device_service] - No libimobiledevice program found, See README Help Center

**Comment by zhaoye** [comment]
libimobiledevice 是一个iOS插件依赖的开源工具。 在无法使用该工具时，插件会输出一行日志。
可以参考 https://github.com/meituan/lyrebird-ios/blob/master/README.md
@Archer456
